FROM mongo:6.0.24@sha256:e1b09da36fbca9e9e6f8464aa85777d685d5677c1f01bd947dc83d0b2332b248

COPY ./dump /docker-entrypoint-initdb.d/dump
COPY ./init.sh /docker-entrypoint-initdb.d/init.sh

RUN chmod +x /docker-entrypoint-initdb.d/init.sh
