name: deploy
services:
  backend:
    build:
      context: /Users/shikiryougi/ryougi-shiky/COMP30022-IT-Project/backend
      dockerfile: Dockerfile.dev
    container_name: backend
    depends_on:
      mongodb:
        condition: service_started
        required: true
    environment:
      CORS_WHITELIST: http://localhost:3000
      MONGODB_NAME: ani
      MONGODB_URI: mongodb://mongodb:27017
      NODE_ENV: development
      PORT: "17000"
    networks:
      app-network: null
    ports:
      - mode: ingress
        target: 17000
        published: "17000"
        protocol: tcp
  mongodb:
    build:
      context: /Users/shikiryougi/ryougi-shiky/COMP30022-IT-Project/db/mongo
      dockerfile: Dockerfile.dev
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ani
    networks:
      app-network: null
    ports:
      - mode: ingress
        target: 27017
        published: "27017"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
        volume: {}
  nginx:
    build:
      context: /Users/shikiryougi/ryougi-shiky/COMP30022-IT-Project
      dockerfile: ./nginx/Dockerfile.dev
    depends_on:
      backend:
        condition: service_started
        required: true
    networks:
      app-network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
networks:
  app-network:
    name: deploy_app-network
    driver: bridge
volumes:
  mongodb_data:
    name: deploy_mongodb_data
