FROM node:22-slim@sha256:c26e3d817a783016e1927a576b12bb262ebdaa9a4338e11ed2f7b31d557289b5

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . .

USER node

EXPOSE 17000
CMD ["npm", "start"]
