FROM node:22-slim@sha256:2fa754a9ba4d7adbd2a51d182eaabbe355c82b673624035a38c0d42b08724854

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . .

USER node

EXPOSE 17000
CMD ["npm", "start"]
