version: "3.9"

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration
      - DEBUG=${DEBUG-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - EDGE_PORT=4566

      # Services to start (only EC2 and EBS as per your requirements)
      - SERVICES=ec2,ebs,iam,sts

      # Data persistence
      - DATA_DIR=/var/lib/localstack
      - PERSISTENCE=1

      # AWS configuration
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

      # Additional settings
      - SKIP_INFRA_DOWNLOADS=0
      - KINESIS_ERROR_PROBABILITY=0.0
      - DYNAMODB_ERROR_PROBABILITY=0.0

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
    networks:
      - localstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Optional: LocalStack Web UI (Pro feature, but we can use community version)
  localstack-web:
    container_name: localstack-web
    image: localstack/localstack-web:latest
    ports:
      - "8080:8080"
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    networks:
      - localstack-network
    profiles:
      - web

networks:
  localstack-network:
    driver: bridge

volumes:
  localstack-data:
