services:
  localstack:
    container_name: localstack-ec2
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,iam
      - DEBUG=1
      - PERSISTENCE=1
      - LOCALSTACK_HOST=localhost
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
