services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ecs,ec2,iam,logs,elbv2,ecr,servicediscovery
      - DEBUG=1
      - PERSISTENCE=1
      - LOCALSTACK_HOST=localhost
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/var/lib/localstack"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
