name: Local Tests

on:
  push:
    branches-ignore:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install Docker Environment
      run: |
        ./auto/install-github-action-env
        
    - name: Run E2E Tests with Local Build
      env:
        ENV: "local"
      run: |
        ./auto/run-e2e-tests

    - name: Report build result
      if: always()
      run: |
        echo "Docker Compose build completed with status ${{ job.status }}" 
