name: PR Kind Labeler

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  add-kind-label:
    if: github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract kind from PR body and add label
        id: extract_kind
        run: |
          ./auto/extract-kind-labels "${{ github.event.pull_request.body }}"

      - name: Add kind labels to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.extract_kind.outputs.labels }}
