name: Publish Docker Images

on:
  push:
    paths:
      - version.txt
    branches:
      - 'release/**'

jobs:
  publish-docker-images:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Environment
      run: ./auto/install-github-action-env

    - name: Read version from version.txt
      id: get_version
      run: ./auto/read-version

    - name: Check if tag already exists
      id: check_tag
      run: ./auto/check-tag "${{ steps.get_version.outputs.VERSION }}"

    - name: Build Docker image
      run: ./auto/build "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ steps.get_version.outputs.VERSION }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Publish Docker image
      run: ./auto/publish-images "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ steps.get_version.outputs.VERSION }}"

    - name: Run E2E Tests with Test Build
      env:
        ENV: "test"
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        ./auto/run-e2e-tests
